name: primitve-serial
version: "0.1"
author: Ashley Yakeley
copyright: (c) 2022 Ashley Yakeley
license: BSD-2-Clause
license-file: LICENSE
maintainer: <ashley@semantic.org>
homepage: https://github.com/AshleyYakeley/primitve-serial
bug-reports: https://github.com/AshleyYakeley/witprimitve-serialness/issues
synopsis: Serialisation of primitive types
description: Representation of basic numeric types as ByteStrings
category: Serialization
build-type: Simple

extra-source-files:
  - changelog.md

library:
    source-dirs: src
    language: GHC2021
    default-extensions:
      - RecordWildCards
    ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Wnoncanonical-monad-instances
      - -Wno-partial-type-signatures
    dependencies:
      - base >= 4.16 && < 5
      - cpu
      - bytestring
    exposed-modules:
      - Data.PrimitiveSerial
